In [80]:
# import numpy as np
# np.version.version
!pip install numpy==1.19

  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'


  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [66 lines of output]
  Running from numpy source directory.
  <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  C:\Users\steve\AppData\Local\Temp\pip-install-d0ch2uuq\numpy_40e9121e6c074be488c47a83bc5641b3\tools\cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    required_version = LooseVersion('0.29.14')
  C:\Users\steve\AppData\Local\Temp\pip-install-d0ch2uuq\numpy_40e9121e6c074be488c47a83bc5641b3\tools\cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(cython_version) < required_version:
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
          for i in range(1, RK_STATE_LEN):
              

In [81]:
# https://www.kaggle.com/datasets/guillemservera/grains-and-cereals-futures
import pandas as pd
grains_df = pd.read_csv('all_grains_data.csv')
grains_df

ticker commodity        date     open     high      low    close  volume
0       ZC=F      Corn  2000-07-17   182.25   182.25   178.25   179.25   19385
1       ZC=F      Corn  2000-07-18   179.00   183.25   179.00   180.75   25205
2       ZC=F      Corn  2000-07-19   180.00   182.75   178.75   182.00   17126
3       ZC=F      Corn  2000-07-20   181.50   187.00   181.00   186.00   18742
4       ZC=F      Corn  2000-07-21   185.50   188.00   185.00   187.75   16814
...      ...       ...         ...      ...      ...      ...      ...     ...
34860   ZS=F   Soybean  2023-09-06  1365.50  1365.50  1359.50  1360.25     102
34861   ZS=F   Soybean  2023-09-07  1349.50  1350.00  1345.00  1345.00     310
34862   ZS=F   Soybean  2023-09-08  1339.00  1349.50  1339.00  1349.50     198
34863   ZS=F   Soybean  2023-09-11  1352.50  1352.50  1352.00  1352.50      36
34864   ZS=F   Soybean  2023-09-12  1344.75  1350.00  1342.50  1343.75    8642

[34865 rows x 8 columns]

In [82]:
grains_df['commodity'].unique()

array(['Corn', 'Oat', 'KC HRW Wheat', 'Rough Rice', 'Soybean Oil',
       'Soybean'], dtype=object)

In [83]:
corn_df = pd.read_csv('individual_data/Corn_data.csv')
corn_df

date    open    high     low   close  volume
0     2000-07-17  182.25  182.25  178.25  179.25   19385
1     2000-07-18  179.00  183.25  179.00  180.75   25205
2     2000-07-19  180.00  182.75  178.75  182.00   17126
3     2000-07-20  181.50  187.00  181.00  186.00   18742
4     2000-07-21  185.50  188.00  185.00  187.75   16814
...          ...     ...     ...     ...     ...     ...
5786  2023-09-06  473.50  476.25  471.25  471.50     841
5787  2023-09-07  471.25  474.00  468.50  470.75     741
5788  2023-09-08  471.25  472.25  467.00  468.50     233
5789  2023-09-11  470.25  471.50  468.00  471.25     430
5790  2023-09-12  476.50  477.75  476.00  476.75    4399

[5791 rows x 6 columns]

In [84]:
corn_dict = {}
window_size = 7
for i in range(window_size):
    corn_dict['price_'+str(7-i)+'_days_ago'] = corn_df['close'][i:-7+i].reset_index(drop=True) 
corn_dict    

{'price_7_days_ago': 0       179.25
 1       180.75
 2       182.00
 3       186.00
 4       187.75
          ...  
 5779    470.75
 5780    478.50
 5781    469.50
 5782    461.75
 5783    461.00
 Name: close, Length: 5784, dtype: float64,
 'price_6_days_ago': 0       180.75
 1       182.00
 2       186.00
 3       187.75
 4       184.50
          ...  
 5779    478.50
 5780    469.50
 5781    461.75
 5782    461.00
 5783    464.75
 Name: close, Length: 5784, dtype: float64,
 'price_5_days_ago': 0       182.00
 1       186.00
 2       187.75
 3       184.50
 4       182.75
          ...  
 5779    469.50
 5780    461.75
 5781    461.00
 5782    464.75
 5783    471.00
 Name: close, Length: 5784, dtype: float64,
 'price_4_days_ago': 0       186.00
 1       187.75
 2       184.50
 3       182.75
 4       180.50
          ...  
 5779    461.75
 5780    461.00
 5781    464.75
 5782    471.00
 5783    471.50
 Name: close, Length: 5784, dtype: float64,
 'price_3_days_ago': 0       187.75
 1  

In [85]:
X = pd.DataFrame.from_dict(corn_dict)
X

price_7_days_ago  price_6_days_ago  price_5_days_ago  price_4_days_ago  \
0               179.25            180.75            182.00            186.00   
1               180.75            182.00            186.00            187.75   
2               182.00            186.00            187.75            184.50   
3               186.00            187.75            184.50            182.75   
4               187.75            184.50            182.75            180.50   
...                ...               ...               ...               ...   
5779            470.75            478.50            469.50            461.75   
5780            478.50            469.50            461.75            461.00   
5781            469.50            461.75            461.00            464.75   
5782            461.75            461.00            464.75            471.00   
5783            461.00            464.75            471.00            471.50   

      price_3_days_ago  price_2_days_ago  price_1_days_ago  
0               187.75            184.50            182.75  
1               184.50            182.75            180.50  
2               182.75            180.50            181.00  
3               180.50            181.00            180.25  
4               181.00            180.25            180.25  
...                ...               ...               ...  
5779            461.00            464.75            471.00  
5780            464.75            471.00            471.50  
5781            471.00            471.50            470.75  
5782            471.50            470.75            468.50  
5783            470.75            468.50            471.25  

[5784 rows x 7 columns]

In [86]:
y = corn_df['close'][7:].reset_index(drop=True) 
y

0       180.50
1       181.00
2       180.25
3       180.25
4       179.75
         ...  
5779    471.50
5780    470.75
5781    468.50
5782    471.25
5783    476.75
Name: close, Length: 5784, dtype: float64

In [87]:
train_pct = .9
X_train = X[:int(len(X)*train_pct)]
X_test = X[int(len(X)*train_pct):]
y_train = y[:int(len(y)*train_pct)]
y_test = y[int(len(y)*train_pct):]

In [88]:
from sklearn.linear_model import LinearRegression
  
classifier = LinearRegression()
classifier.fit(X_train, y_train)

LinearRegression()

In [89]:
print (classifier.score(X_train, y_train))
print(classifier.score(X_test, y_test))
# very high coefficient of determination on the train set, lower on the test set

0.9971498308553326
0.971229819095482


In [90]:
y_train_pred = classifier.predict(X_train)
y_test_pred = classifier.predict(X_test)
from sklearn.metrics import mean_squared_error
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
print(train_mse, test_mse)
# mse considerably higher on test set than train set
# higher in general than I would have thought. maybe I should compare these scores to a simple naive prediction using 
# the previous value.

65.14954633823858 193.58699139121558


In [91]:
y_train_pred

array([183.1865224 , 180.69614961, 181.4084901 , ..., 656.58183816,
       664.93181076, 658.73352565])

In [92]:
y_train

0       180.50
1       181.00
2       180.25
3       180.25
4       179.75
         ...  
5200    658.25
5201    658.25
5202    664.50
5203    659.50
5204    657.25
Name: close, Length: 5205, dtype: float64

In [93]:
X_train = X_train.to_numpy()

In [94]:
X_train

array([[179.25, 180.75, 182.  , ..., 187.75, 184.5 , 182.75],
       [180.75, 182.  , 186.  , ..., 184.5 , 182.75, 180.5 ],
       [182.  , 186.  , 187.75, ..., 182.75, 180.5 , 181.  ],
       ...,
       [759.5 , 757.5 , 719.  , ..., 652.5 , 658.25, 658.25],
       [757.5 , 719.  , 685.  , ..., 658.25, 658.25, 664.5 ],
       [719.  , 685.  , 652.5 , ..., 658.25, 664.5 , 659.5 ]])

In [98]:
X_train = X_train[:,None,:]
X_train

In [99]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
# create and fit the LSTM network
model = Sequential()
model.add(LSTM(4, input_shape=(1,7)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=2)

Epoch 1/100
5205/5205 - 7s - loss: 167048.3281 - 7s/epoch - 1ms/step
Epoch 2/100
5205/5205 - 5s - loss: 160675.8438 - 5s/epoch - 1ms/step
Epoch 3/100
5205/5205 - 6s - loss: 154471.4844 - 6s/epoch - 1ms/step
Epoch 4/100
5205/5205 - 6s - loss: 148428.2188 - 6s/epoch - 1ms/step
Epoch 5/100
5205/5205 - 6s - loss: 142558.4375 - 6s/epoch - 1ms/step
Epoch 6/100
5205/5205 - 6s - loss: 136845.8438 - 6s/epoch - 1ms/step
Epoch 7/100
5205/5205 - 6s - loss: 131311.3906 - 6s/epoch - 1ms/step
Epoch 8/100
5205/5205 - 6s - loss: 125929.3359 - 6s/epoch - 1ms/step
Epoch 9/100
5205/5205 - 6s - loss: 120703.1172 - 6s/epoch - 1ms/step
Epoch 10/100
5205/5205 - 6s - loss: 115626.2109 - 6s/epoch - 1ms/step
Epoch 11/100
5205/5205 - 6s - loss: 110721.2031 - 6s/epoch - 1ms/step
Epoch 12/100
5205/5205 - 6s - loss: 105981.3906 - 6s/epoch - 1ms/step
Epoch 13/100
5205/5205 - 6s - loss: 101420.3281 - 6s/epoch - 1ms/step
Epoch 14/100
5205/5205 - 6s - loss: 96978.4141 - 6s/epoch - 1ms/step
Epoch 15/100
5205/5205 - 6s - 

In [100]:
X_test = X_test.to_numpy()
X_test = X_test[:,None,:]
X_test

array([[[685.  , 652.5 , 658.25, ..., 664.5 , 659.5 , 657.25]],

       [[652.5 , 658.25, 658.25, ..., 659.5 , 657.25, 620.25]],

       [[658.25, 658.25, 664.5 , ..., 657.25, 620.25, 624.5 ]],

       ...,

       [[469.5 , 461.75, 461.  , ..., 471.  , 471.5 , 470.75]],

       [[461.75, 461.  , 464.75, ..., 471.5 , 470.75, 468.5 ]],

       [[461.  , 464.75, 471.  , ..., 470.75, 468.5 , 471.25]]])

In [102]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
from sklearn.metrics import mean_squared_error
train_mse = mean_squared_error(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
print(train_mse, test_mse)
# higher mse

19/19 [==============================] - 0s 765us/step
22865.94781335876 71500.14079386462
